### ISSUE TITLE
feature extracted from image encoder

### ISSUE THREAD

**Issue by zdk258** [dogehhh/ReCLIP#3]
作者您好。在image encoder的最后一层中：
```
    def forward(self, x: torch.Tensor):
        y = self.ln_1(x)
        y = F.linear(y, self.attn.in_proj_weight, self.attn.in_proj_bias)
        N, L, C = y.shape
        y = y.view(N, L, 3, C // 3).permute(2, 0, 1, 3).reshape(3 * N, L, C // 3)
        y = F.linear(y, self.attn.out_proj.weight, self.attn.out_proj.bias)
        q, k, v = y.tensor_split(3, dim=0)
        v += x
        v = v + self.mlp(self.ln_2(v))
        x = x + self.attention(self.ln_1(x))
        x = x + self.mlp(self.ln_2(x))
        out = [x, q, k, v]
        return out
```
原文中说

> We remove the query and key embedding layers of last attention but reformulate the value embedding layer and the last linear projection layer into two respective 1×1 convolutional layers

为什么v+=x，并且后面还要计算x呢？

**Comment by dogehhh** [comment]
We choose MaskCLIP as our baseline and the architecture of our image encoder is taken from the official code of MaskCLIP. In fact, this is a modification on attention mechanism in order to generate patch-level dense features. Though we compute x
here, the following operation is conducted on v and you can ignore the computation of x here.
